# Generated by Django 4.2 on 2024-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_usercustom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustom",
            name="name",
            field=models.CharField(default="Unknown", max_length=25),
        ),
    ]
