# Generated by Django 5.0.1 on 2024-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="pthto",
            field=models.ImageField(upload_to="gallery/%Y/%m/%d/"),
        ),
    ]
