# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from account.models import UserCustom

class DongServiceDataEstimateTestFullFin(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.IntegerField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    아파트_단지_수 = models.IntegerField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.IntegerField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.IntegerField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_문화_지출_총금액 = models.FloatField(blank=True, null=True)
    기타_지출_총금액 = models.FloatField(blank=True, null=True)
    음식_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.IntegerField(blank=True, null=True)
    아파트_가구_수 = models.IntegerField(blank=True, null=True)
    비_아파트_가구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dong_service_data_estimate_test_full_fin'


class DongServiceDataPredictTestFullFin(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.IntegerField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    아파트_단지_수 = models.IntegerField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.IntegerField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.IntegerField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_문화_지출_총금액 = models.FloatField(blank=True, null=True)
    기타_지출_총금액 = models.FloatField(blank=True, null=True)
    음식_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.IntegerField(blank=True, null=True)
    아파트_가구_수 = models.IntegerField(blank=True, null=True)
    비_아파트_가구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dong_service_data_predict_test_full_fin'


class DongServiceEstimateShapValues(models.Model):
    행정동_코드 = models.IntegerField(blank=True, primary_key = True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    점포_수 = models.FloatField(blank=True, null=True)
    개업_율 = models.FloatField(blank=True, null=True)
    개업_점포_수 = models.FloatField(blank=True, null=True)
    폐업_률 = models.FloatField(blank=True, null=True)
    폐업_점포_수 = models.FloatField(blank=True, null=True)
    프랜차이즈_점포_수 = models.FloatField(blank=True, null=True)
    아파트_단지_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.FloatField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_문화_지출_총금액 = models.FloatField(blank=True, null=True)
    기타_지출_총금액 = models.FloatField(blank=True, null=True)
    음식_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    아파트_가구_수 = models.FloatField(blank=True, null=True)
    비_아파트_가구_수 = models.FloatField(blank=True, null=True)
    연령대_10_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.FloatField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dong_service_estimate_shap_values'


class DongServiceEstimateY(models.Model):
    행정동_코드 = models.IntegerField(blank=True, primary_key = True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    prediction_label = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dong_service_estimate_y'


class DongSortedDbFin(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    당월_매출_금액 = models.FloatField(blank=True, null=True)
    당월_매출_건수 = models.IntegerField(blank=True, null=True)
    주중_매출_금액 = models.FloatField(blank=True, null=True)
    주말_매출_금액 = models.FloatField(blank=True, null=True)
    월요일_매출_금액 = models.FloatField(blank=True, null=True)
    화요일_매출_금액 = models.FloatField(blank=True, null=True)
    수요일_매출_금액 = models.FloatField(blank=True, null=True)
    목요일_매출_금액 = models.FloatField(blank=True, null=True)
    금요일_매출_금액 = models.FloatField(blank=True, null=True)
    토요일_매출_금액 = models.FloatField(blank=True, null=True)
    일요일_매출_금액 = models.FloatField(blank=True, null=True)
    시간대_00_06_매출_금액 = models.FloatField(db_column='시간대_00_06_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_06_11_매출_금액 = models.FloatField(db_column='시간대_06_11_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_11_14_매출_금액 = models.FloatField(db_column='시간대_11_14_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_14_17_매출_금액 = models.FloatField(db_column='시간대_14_17_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_17_21_매출_금액 = models.FloatField(db_column='시간대_17_21_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_21_24_매출_금액 = models.FloatField(db_column='시간대_21_24_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    남성_매출_금액 = models.FloatField(blank=True, null=True)
    여성_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_10_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_20_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_30_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_40_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_50_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_60_이상_매출_금액 = models.FloatField(blank=True, null=True)
    주중_매출_건수 = models.IntegerField(blank=True, null=True)
    주말_매출_건수 = models.IntegerField(blank=True, null=True)
    월요일_매출_건수 = models.IntegerField(blank=True, null=True)
    화요일_매출_건수 = models.IntegerField(blank=True, null=True)
    수요일_매출_건수 = models.IntegerField(blank=True, null=True)
    목요일_매출_건수 = models.IntegerField(blank=True, null=True)
    금요일_매출_건수 = models.IntegerField(blank=True, null=True)
    토요일_매출_건수 = models.IntegerField(blank=True, null=True)
    일요일_매출_건수 = models.IntegerField(blank=True, null=True)
    시간대_건수_06_매출_건수 = models.IntegerField(db_column='시간대_건수_06_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_11_매출_건수 = models.IntegerField(db_column='시간대_건수_11_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_14_매출_건수 = models.IntegerField(db_column='시간대_건수_14_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_17_매출_건수 = models.IntegerField(db_column='시간대_건수_17_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_21_매출_건수 = models.IntegerField(db_column='시간대_건수_21_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_24_매출_건수 = models.IntegerField(db_column='시간대_건수_24_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    남성_매출_건수 = models.IntegerField(blank=True, null=True)
    여성_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_10_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_20_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_30_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_40_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_50_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_매출_건수 = models.IntegerField(blank=True, null=True)
    집객시설_수 = models.FloatField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    총_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_10_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_20_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_30_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_40_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_50_직장_인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_60_이상_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_10_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_20_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_30_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_40_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_50_직장_인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_60_이상_직장_인구_수 = models.IntegerField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    유사_업종_점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    아파트_단지_수 = models.IntegerField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.IntegerField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.IntegerField(blank=True, null=True)
    소득_구간_코드 = models.IntegerField(blank=True, null=True)
    지출_총금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_문화_지출_총금액 = models.FloatField(blank=True, null=True)
    기타_지출_총금액 = models.FloatField(blank=True, null=True)
    음식_지출_총금액 = models.FloatField(blank=True, null=True)
    총_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_상주인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_10_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_20_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_30_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_40_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_50_상주인구_수 = models.IntegerField(blank=True, null=True)
    남성연령대_60_이상_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_10_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_20_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_30_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_40_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_50_상주인구_수 = models.IntegerField(blank=True, null=True)
    여성연령대_60_이상_상주인구_수 = models.IntegerField(blank=True, null=True)
    총_가구_수 = models.IntegerField(blank=True, null=True)
    아파트_가구_수 = models.IntegerField(blank=True, null=True)
    비_아파트_가구_수 = models.IntegerField(blank=True, null=True)
    총_유동인구_수 = models.IntegerField(blank=True, null=True)
    남성_유동인구_수 = models.IntegerField(blank=True, null=True)
    여성_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    월요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    화요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    수요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    목요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    금요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    토요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    일요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dong_sorted_db_fin'


class MarketServiceDataEstimateTestFull(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    상권_구분_코드 = models.TextField(blank=True, null=True)
    상권_구분_코드_명 = models.TextField(blank=True, null=True)
    상권_코드 = models.IntegerField(blank=True, null=True)
    상권_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    자치구_코드 = models.IntegerField(blank=True, null=True)
    자치구_코드_명 = models.TextField(blank=True, null=True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    아파트_단지_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.FloatField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_지출_총금액 = models.FloatField(blank=True, null=True)
    문화_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    아파트_가구_수 = models.FloatField(blank=True, null=True)
    비_아파트_가구_수 = models.FloatField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)
    주중_평균_유동인구 = models.FloatField(blank=True, null=True)
    주말_평균_유동인구 = models.FloatField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'market_service_data_estimate_test_full'


class MarketServiceDataPredictTestFull(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    상권_구분_코드 = models.TextField(blank=True, null=True)
    상권_구분_코드_명 = models.TextField(blank=True, null=True)
    상권_코드 = models.IntegerField(blank=True, null=True)
    상권_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    자치구_코드 = models.IntegerField(blank=True, null=True)
    자치구_코드_명 = models.TextField(blank=True, null=True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    아파트_단지_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.FloatField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_지출_총금액 = models.FloatField(blank=True, null=True)
    문화_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    아파트_가구_수 = models.FloatField(blank=True, null=True)
    비_아파트_가구_수 = models.FloatField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)
    주중_평균_유동인구 = models.FloatField(blank=True, null=True)
    주말_평균_유동인구 = models.FloatField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'market_service_data_predict_test_full'


class MarketServiceEstimateShapValues(models.Model):
    상권_코드 = models.IntegerField(blank=True, primary_key = True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    점포_수 = models.FloatField(blank=True, null=True)
    개업_율 = models.FloatField(blank=True, null=True)
    개업_점포_수 = models.FloatField(blank=True, null=True)
    폐업_률 = models.FloatField(blank=True, null=True)
    폐업_점포_수 = models.FloatField(blank=True, null=True)
    프랜차이즈_점포_수 = models.FloatField(blank=True, null=True)
    아파트_단지_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.FloatField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_지출_총금액 = models.FloatField(blank=True, null=True)
    문화_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    연령대_10_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.FloatField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.FloatField(blank=True, null=True)
    연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    아파트_가구_수 = models.FloatField(blank=True, null=True)
    비_아파트_가구_수 = models.FloatField(blank=True, null=True)
    주중_평균_유동인구 = models.FloatField(blank=True, null=True)
    주말_평균_유동인구 = models.FloatField(blank=True, null=True)
    전년도_점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'market_service_estimate_shap_values'


class MarketServiceEstimateY(models.Model):
    상권_코드 = models.IntegerField(blank=True, primary_key = True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    prediction_label = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'market_service_estimate_y'


class MarketSortedDbFin(models.Model):
    기준_년분기_코드 = models.IntegerField(blank=True, primary_key = True)
    상권_구분_코드 = models.TextField(blank=True, null=True)
    상권_구분_코드_명 = models.TextField(blank=True, null=True)
    상권_코드 = models.IntegerField(blank=True, null=True)
    상권_코드_명 = models.TextField(blank=True, null=True)
    서비스_업종_코드 = models.TextField(blank=True, null=True)
    서비스_업종_코드_명 = models.TextField(blank=True, null=True)
    당월_매출_금액 = models.FloatField(blank=True, null=True)
    당월_매출_건수 = models.IntegerField(blank=True, null=True)
    주중_매출_금액 = models.FloatField(blank=True, null=True)
    주말_매출_금액 = models.FloatField(blank=True, null=True)
    월요일_매출_금액 = models.FloatField(blank=True, null=True)
    화요일_매출_금액 = models.FloatField(blank=True, null=True)
    수요일_매출_금액 = models.FloatField(blank=True, null=True)
    목요일_매출_금액 = models.FloatField(blank=True, null=True)
    금요일_매출_금액 = models.FloatField(blank=True, null=True)
    토요일_매출_금액 = models.FloatField(blank=True, null=True)
    일요일_매출_금액 = models.FloatField(blank=True, null=True)
    시간대_00_06_매출_금액 = models.FloatField(db_column='시간대_00_06_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_06_11_매출_금액 = models.FloatField(db_column='시간대_06_11_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_11_14_매출_금액 = models.FloatField(db_column='시간대_11_14_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_14_17_매출_금액 = models.FloatField(db_column='시간대_14_17_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_17_21_매출_금액 = models.FloatField(db_column='시간대_17_21_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_21_24_매출_금액 = models.FloatField(db_column='시간대_21_24_매출_금액', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    남성_매출_금액 = models.FloatField(blank=True, null=True)
    여성_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_10_매출_금액 = models.IntegerField(blank=True, null=True)
    연령대_20_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_30_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_40_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_50_매출_금액 = models.FloatField(blank=True, null=True)
    연령대_60_이상_매출_금액 = models.FloatField(blank=True, null=True)
    주중_매출_건수 = models.IntegerField(blank=True, null=True)
    주말_매출_건수 = models.IntegerField(blank=True, null=True)
    월요일_매출_건수 = models.IntegerField(blank=True, null=True)
    화요일_매출_건수 = models.IntegerField(blank=True, null=True)
    수요일_매출_건수 = models.IntegerField(blank=True, null=True)
    목요일_매출_건수 = models.IntegerField(blank=True, null=True)
    금요일_매출_건수 = models.IntegerField(blank=True, null=True)
    토요일_매출_건수 = models.IntegerField(blank=True, null=True)
    일요일_매출_건수 = models.IntegerField(blank=True, null=True)
    시간대_건수_06_매출_건수 = models.IntegerField(db_column='시간대_건수_06_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_11_매출_건수 = models.IntegerField(db_column='시간대_건수_11_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_14_매출_건수 = models.IntegerField(db_column='시간대_건수_14_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_17_매출_건수 = models.IntegerField(db_column='시간대_건수_17_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_21_매출_건수 = models.IntegerField(db_column='시간대_건수_21_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    시간대_건수_24_매출_건수 = models.IntegerField(db_column='시간대_건수_24_매출_건수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    남성_매출_건수 = models.IntegerField(blank=True, null=True)
    여성_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_10_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_20_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_30_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_40_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_50_매출_건수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_매출_건수 = models.IntegerField(blank=True, null=True)
    집객시설_수 = models.FloatField(blank=True, null=True)
    관공서_수 = models.FloatField(blank=True, null=True)
    은행_수 = models.FloatField(blank=True, null=True)
    종합병원_수 = models.FloatField(blank=True, null=True)
    일반_병원_수 = models.FloatField(blank=True, null=True)
    약국_수 = models.FloatField(blank=True, null=True)
    유치원_수 = models.FloatField(blank=True, null=True)
    초등학교_수 = models.FloatField(blank=True, null=True)
    중학교_수 = models.FloatField(blank=True, null=True)
    고등학교_수 = models.FloatField(blank=True, null=True)
    대학교_수 = models.FloatField(blank=True, null=True)
    백화점_수 = models.FloatField(blank=True, null=True)
    슈퍼마켓_수 = models.FloatField(blank=True, null=True)
    극장_수 = models.FloatField(blank=True, null=True)
    숙박_시설_수 = models.FloatField(blank=True, null=True)
    공항_수 = models.FloatField(blank=True, null=True)
    철도_역_수 = models.FloatField(blank=True, null=True)
    버스_터미널_수 = models.FloatField(blank=True, null=True)
    지하철_역_수 = models.FloatField(blank=True, null=True)
    버스_정거장_수 = models.FloatField(blank=True, null=True)
    총_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_10_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_20_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_30_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_40_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_50_직장_인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_60_이상_직장_인구_수 = models.FloatField(blank=True, null=True)
    점포_수 = models.IntegerField(blank=True, null=True)
    유사_업종_점포_수 = models.IntegerField(blank=True, null=True)
    개업_율 = models.IntegerField(blank=True, null=True)
    개업_점포_수 = models.IntegerField(blank=True, null=True)
    폐업_률 = models.IntegerField(blank=True, null=True)
    폐업_점포_수 = models.IntegerField(blank=True, null=True)
    프랜차이즈_점포_수 = models.IntegerField(blank=True, null=True)
    엑스좌표_값 = models.IntegerField(blank=True, null=True)
    와이좌표_값 = models.IntegerField(blank=True, null=True)
    자치구_코드 = models.IntegerField(blank=True, null=True)
    자치구_코드_명 = models.TextField(blank=True, null=True)
    행정동_코드 = models.IntegerField(blank=True, null=True)
    행정동_코드_명 = models.TextField(blank=True, null=True)
    영역_면적 = models.IntegerField(blank=True, null=True)
    아파트_단지_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_66_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_99_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_132_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_면적_165_제곱미터_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_미만_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_1_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_2_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_3_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_4_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_5_억_세대_수 = models.FloatField(blank=True, null=True)
    아파트_가격_6_억_이상_세대_수 = models.FloatField(blank=True, null=True)
    아파트_평균_면적 = models.FloatField(blank=True, null=True)
    아파트_평균_시가 = models.FloatField(blank=True, null=True)
    월_평균_소득_금액 = models.FloatField(blank=True, null=True)
    소득_구간_코드 = models.FloatField(blank=True, null=True)
    지출_총금액 = models.FloatField(blank=True, null=True)
    식료품_지출_총금액 = models.FloatField(blank=True, null=True)
    의류_신발_지출_총금액 = models.FloatField(blank=True, null=True)
    생활용품_지출_총금액 = models.FloatField(blank=True, null=True)
    의료비_지출_총금액 = models.FloatField(blank=True, null=True)
    교통_지출_총금액 = models.FloatField(blank=True, null=True)
    여가_지출_총금액 = models.FloatField(blank=True, null=True)
    문화_지출_총금액 = models.FloatField(blank=True, null=True)
    교육_지출_총금액 = models.FloatField(blank=True, null=True)
    유흥_지출_총금액 = models.FloatField(blank=True, null=True)
    총_유동인구_수 = models.IntegerField(blank=True, null=True)
    남성_유동인구_수 = models.IntegerField(blank=True, null=True)
    여성_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_10_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_20_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_30_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_40_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_50_유동인구_수 = models.IntegerField(blank=True, null=True)
    연령대_60_이상_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_00_06_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_06_11_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_11_14_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_14_17_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_17_21_유동인구_수 = models.IntegerField(blank=True, null=True)
    시간대_21_24_유동인구_수 = models.IntegerField(blank=True, null=True)
    월요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    화요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    수요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    목요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    금요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    토요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    일요일_유동인구_수 = models.IntegerField(blank=True, null=True)
    총_상주인구_수 = models.FloatField(blank=True, null=True)
    남성_상주인구_수 = models.FloatField(blank=True, null=True)
    여성_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    남성연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_10_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_20_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_30_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_40_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_50_상주인구_수 = models.FloatField(blank=True, null=True)
    여성연령대_60_이상_상주인구_수 = models.FloatField(blank=True, null=True)
    총_가구_수 = models.FloatField(blank=True, null=True)
    아파트_가구_수 = models.FloatField(blank=True, null=True)
    비_아파트_가구_수 = models.FloatField(blank=True, null=True)
    점포별_평균_매출_금액 = models.FloatField(blank=True, null=True)
    분기 = models.IntegerField(blank=True, null=True)
    코로나_여부 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'market_sorted_db_fin'



class AiReport(models.Model):
    report_id = models.AutoField(primary_key=True)
    creationdate = models.DateTimeField(auto_now_add=True)
    region = models.CharField(max_length=20)
    area_1 = models.CharField(max_length=20)
    area_2 = models.CharField(max_length=20, blank=True, null=True)
    business = models.CharField(max_length=20)
    funds = models.BigIntegerField()
    sales_23_2q = models.BigIntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    esti_23_3q = models.BigIntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    pred_23_4q = models.BigIntegerField(blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    top_influ = models.JSONField(blank=True, null=True)
    bottom_influ = models.JSONField(blank=True, null=True)
    sim_result = models.CharField(max_length=10, blank=True, null=True)
    avg_sale_comp = models.CharField(max_length=45, blank=True, null=True)
    sale_updown = models.CharField(max_length=45, blank=True, null=True)
    market_active = models.CharField(max_length=45, blank=True, null=True)
    opening_updown = models.CharField(max_length=45, blank=True, null=True)
    area_growth = models.CharField(max_length=45, blank=True, null=True)
    fpeople_updown = models.CharField(max_length=45, blank=True, null=True)
    simil_area_name_1 = models.CharField(max_length=20, blank=True, null=True)
    simil_area_esti_1 = models.BigIntegerField(blank=True, null=True)
    simil_area_diff_1 = models.BigIntegerField(blank=True, null=True)
    simil_area_name_2 = models.CharField(max_length=20, blank=True, null=True)  # Field renamed to remove unsuitable characters. Field renamed because it ended with '_'.
    simil_area_esti_2 = models.BigIntegerField(blank=True, null=True)
    simil_area_diff_2 = models.BigIntegerField(blank=True, null=True)
    AI = models.CharField(db_column='AI', max_length=10)  # Field name made lowercase.
    user = models.ForeignKey(UserCustom, models.DO_NOTHING)
    rent_cost = models.IntegerField(blank=True, null=True)
    posi_fran_num = models.IntegerField(blank=True, null=True)
    franchise_rec_1 = models.JSONField(blank=True, null=True)
    franchise_rec_2 = models.JSONField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ai_report'
        
        
        
#############################################################
#                      프랜차이즈                            #
#############################################################
class Vacancyrate(models.Model):
    지역별 = models.TextField(primary_key = True)
    상세지역 = models.TextField(blank=True, null=True)
    임대료 = models.FloatField(blank=True, null=True)
    평균임대면적 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'vacancyrate'


class SeoulRent(models.Model):
    dong_code = models.IntegerField(primary_key = True)
    dong_name = models.TextField(blank=True, null=True)
    area_size = models.IntegerField(blank=True, null=True)
    x = models.IntegerField(blank=True, null=True)
    y = models.BigIntegerField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    latituded = models.FloatField(blank=True, null=True)
    area_name = models.TextField(blank=True, null=True)
    시도명 = models.TextField(blank=True, null=True)
    시군구명 = models.TextField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'seoul_rent'


class FranchiseData(models.Model):
    대분류서비스 = models.TextField(blank=True, null=True)
    중분류서비스 = models.TextField(blank=True, null=True)
    법인명 = models.TextField(blank=True, null=True)
    브랜드명 = models.TextField(primary_key = True)
    가맹점수 = models.IntegerField(blank=True, null=True)
    신규가맹점_등록수 = models.IntegerField(db_column='신규가맹점 등록수', blank=True, null=True)  # Field renamed to remove unsuitable characters.
    계약종료수 = models.IntegerField(blank=True, null=True)
    계약해지수 = models.IntegerField(blank=True, null=True)
    명의변경수 = models.IntegerField(blank=True, null=True)
    평균매출금액 = models.IntegerField(blank=True, null=True)
    면적단위평균매출액 = models.IntegerField(blank=True, null=True)
    가맹금액 = models.IntegerField(blank=True, null=True)
    교육금액 = models.IntegerField(blank=True, null=True)
    보증금액 = models.IntegerField(blank=True, null=True)
    기타금액 = models.IntegerField(blank=True, null=True)
    합계금액 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'franchise_data'