"""
Django settings for dev project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

SELECT_DATABASE = 0 # 0: AWS MySQL 사용  //  1: Local MySQL 사용  //  2: Django의 기본 SQLite 사용


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

sensitiveDataPath = ('C:/Users/suhwan/Desktop/2023_big/data/djangoSecretKey_info.txt')
sensitiveData = open(sensitiveDataPath, 'r')
django_secretKey = sensitiveData.readline()
sensitiveData.close()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secretKey[:-1]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.forms',
    
    # 사이트 기능
    "account",
    'analysis',
    'board',
    'faq',
    'report',
    'suggestions',
    
    # rest API
    "rest_framework",
    "corsheaders",

    # test API (custom api)
    "testapi"
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.AllowAny',
    ]
}

sensitiveDataPath = ('C:/Users/suhwan/Desktop/2023_big/data/frontURL_info.txt')
sensitiveData = open(sensitiveDataPath, 'r')
frontURL = sensitiveData.readline()
sensitiveData.close()

CORS_ORIGIN_WHITELIST = [
    frontURL[:-1],
]

MIDDLEWARE = [
    # rest API를 위한 middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # django 기본 middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dev.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dev.wsgi.application"

sensitiveDataPath = ('C:/Users/suhwan/Desktop/2023_big/data/DB_info.txt')
sensitiveData = open(sensitiveDataPath, 'r')
sensitiveDataList = []

while True:
    line = sensitiveData.readline()
    if not line: break
    else: sensitiveDataList.append(line)
sensitiveData.close()
sensitiveDataList

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if SELECT_DATABASE == 0 :
    DATABASES = {
        'default' : {
            'ENGINE': sensitiveDataList[0][:-1],    
            'NAME': sensitiveDataList[1][:-1],                  
            'USER': sensitiveDataList[2][:-1],                          
            'PASSWORD': sensitiveDataList[3][:-1],                  
            'HOST': sensitiveDataList[4][:-1],                     
            'PORT': sensitiveDataList[5][:-1],
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'use_unicode': True,
            },                          
        }
    }
    
elif SELECT_DATABASE == 1:
    DATABASES = { 
        'default': {
            'ENGINE': sensitiveDataList[6][:-1],
            'NAME': sensitiveDataList[7][:-1],
            'USER': sensitiveDataList[8][:-1],
            'PASSWORD': sensitiveDataList[9][:-1],
            'HOST': sensitiveDataList[10][:-1],
            'PORT': sensitiveDataList[11][:-1],
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
                'use_unicode': True,
            },
        }
    }
    
else: 
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "chinook.db",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ORIGIN_WHITELIST = ('http://127.0.0.1:8000','http://127.0.0.1:3000', 'http://localhost:3000')
CORS_ALLOW_CREDENTIALS = True