# Generated by Django 5.0.1 on 2024-01-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="uploaded_on",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
