# Generated by Django 5.0.1 on 2024-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0002_remove_uploadedfile_uploaded_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploaded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
