# Generated by Django 5.0.1 on 2024-01-10 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0003_uploaded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="description",
            new_name="uploaded_on",
        ),
    ]
